[package]
name = "tinc-gui"
version = "0.1.0"
authors = ["yanbowen1994 <511838976@qq.com>"]
edition = "2018"

[dependencies]
futures = "0.3.1"
iced = { git = "https://github.com/hecrj/iced.git", branch = "master" }